# Eve Horizon Dashboard Manifest
schema: eve/compose/v2
project: eve-horizon-dashboard

x-eve:
  defaults:
    env: staging
    hints:
      harness: mclaude
  requires:
    secrets:
      - GHCR_USERNAME
      - GITHUB_TOKEN

registry:
  host: ghcr.io
  namespace: incept5
  auth:
    username_secret: GHCR_USERNAME
    token_secret: GITHUB_TOKEN

environments:
  test:
    type: persistent
  staging:
    type: persistent

services:
  dashboard:
    build:
      context: apps/api
    image: ghcr.io/incept5/eve-horizon-dashboard:latest
    ports: [3000]
    environment:
      NODE_ENV: production
      # EVE_API_URL, EVE_PROJECT_ID, EVE_ORG_ID, EVE_ENV_NAME are auto-injected by Eve
    healthcheck:
      test: curl -f http://localhost:3000/health || exit 1
    x-eve:
      ingress:
        public: true
        port: 3000

pipelines:
  deploy:
    steps:
      - name: deploy
        action:
          type: deploy
